name: Dismantle
main: nl.nitori.Dismantle.DismantleMain
version: 1
commands:
   dismantle:
      description: Takes apart items
      usage: /dismantle - While holding a valid item (armor, tool)
      permission: dismantle.use
      permission-message: You don't have permission to use /dismantle